# Project
version = 0.1.6.2
group = it.hurts.octostudios.perception
java_version = 25

# Common
minecraft_version = 26.2
mod_name = Perception
mod_author = OctoStudios
mod_id = perception
license = All Rights Reserved
credits =
description = Enriching the world with immersive visual effects
mod_tracker = https://github.com/Octo-Studios/perception/issues
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

# Fabric
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)

# Dependencies
shatterlib_version = 0.7.0-beta.1+26.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
#org.gradle.daemon=false
